### ISSUE TITLE
Pourquoi une licence GPL?

### ISSUE THREAD

**Issue by bzg** [numerique-gouv/proconnect-kitchen-sink#1]
Hello, par défaut, la DINUM recommande d'utiliser des licences libres permissives comme la MIT ou la Apache 2.0.

Voir https://code.gouv.fr/guides/juridique/

S'il n'y a pas de raison d'utiliser une licence à réciprocité, peut-on en envisager une autre?

**Comment by douglasduteil** [comment]
My bad @bzg 
On peut totalement en changer.
@rdubigny je m'aligne sur ta licence ?
https://github.com/numerique-gouv/moncomptepro/blob/master/LICENSE

**Comment by bzg** [comment]
Merci pour ton retour ! La licence Affero GPL est à réciprocité _forte_, ça va dans la mauvaise direction :)

Une MIT, Apache 2.0, BSD (2 ou 3) ne pose aucun souci.

Cf. https://git.sr.ht/~codegouvfr/codegouvfr-fetch-data/tree/main/item/LICENSE.md par exemple.

**Comment by douglasduteil** [comment]
C'est fait @bzg 
\cc @rdubigny a noter pour nos autres repos ProConnect :eyes:

**Comment by bzg** [comment]
Merci !

**Comment by rdubigny** [comment]
J'ai vu, je crée un ticket
